openshift/builder

pkg/build/builder/dockerutil.go, pkg/build/builder/dockerutil_test.go
Per conversation in https://github.com/openshift/origin/pull/20941, this:
- Modifies `RetryImageAction`→`retryImageAction` to use a callback instead of containing parts of the calling functions and using reflection to choose which part to call. This could reportedly be useful for the `buildah`-based implementation as well.
- Fixes `dockerPushImage`/`dockerPullImage` to correctly detect errors reported through the `imageprogress` channel. These functions don’t have any callers outside of tests anymore, so this is not really interesting — but this preserves the bug fixes in case they were revived, and I needed to updated them for the `retryImageAction` changes to build anyway.
Manually tested only using `go test ./...`; hoping the CI can handle the bigger picture.
=> callback-based retryImageAction + Don't ignore errors reported during Docker push/pull

pkg/build/builder/docker.go
Replace direct calls to dockerClient.PullImage() and dockerClient.PushImage() with calls that wrap them in retryImageAction(), so that we will retry them if either fail due to what appears to be a transient error.
=> Retry pulling or pushing images, for certain errors

imagecontent/storage.conf
Causes the following warning in builds:
time="2018-11-12T20:04:10Z" level=warning msg="Not using native diff for overlay, this may cause degraded performance for building images: failed to mount overlay: invalid argument"
we can see the following in dmseg
[63095.446247] overlayfs: unrecognized mount option "nodev" or missing value
Applying nodev everywhere is also not right and we already
revomed/reverted such behavior recently introduced in CRI-O.
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> imagecontent/storage.conf: remove nodev from mountopt

cmd/main.go
=> Revert "copy build certificates to /etc/docker/certs.d"

cmd/main.go
Restores functionality in #29
Reverts #30
=> Restore "copy build certificates to /etc/docker/certs.d"

Dockerfile, Dockerfile-dev, Dockerfile.rhel7
https://bugzilla.redhat.com/show_bug.cgi?id=1677818 causes an error
when we run rpm -V on findutils. While we transition to microdnf
remove the verification check (which protects against an issue
that only yum has but microdnf/dnf do not have).
=> Workaround bug 1677818 in microdnf for new UBI base images

pkg/build/builder/sti.go
Wrap S2IBuilder.pullImage's attempts to pull an image with retryImageAction(), to match its push logic and the pull and push logic that we use for builds that use the Docker strategy.
This should fix #45.
=> S2IBuilder.pullImage: retry pulls

pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_unsupported.go, pkg/build/builder/docker.go, pkg/build/builder/docker_test.go, pkg/build/builder/dockerutil.go, pkg/build/builder/dockerutil_test.go, pkg/build/builder/source.go
Remove copyImageSource(), and the DownloadFromContainer() interface member and its daemonless implementation, which we're not using.
=> Drop unused copyImageSource() function

pkg/build/builder/dockerutil_test.go, pkg/build/builder/sti.go, pkg/build/builder/sti_test.go
* Attempt to pull the output image for incremental s2i builds.
* If incremental image does not exist, revert back to a normal s2i build.
Fixes [Bug 1688779](https://bugzilla.redhat.com/show_bug.cgi?id=1688779)
=> Bug 1688779: Ensure image exists for incremental builds

pkg/build/builder/source.go
Adding "trace" logs to print output from bsdtar.
This is explicitly not a part of the normal debug logging - outside of a current [known bug](https://bugzilla.redhat.com/show_bug.cgi?id=1673806) builds should not fail extracting binary source.
/assign @coreydaley
=> Add verbose output for bsdtar

pkg/build/builder/source.go, pkg/build/builder/source_test.go
* Fix copy behavior if the image source path ends with "/."
* Add unit tests for copying regular files and symlinks
/assign @coreydaley 
/cc @bparees 
fyi @openshift/sig-developer-experience
=> Bug 1698152: fix image source extraction with trailing "/."

pkg/build/builder/sti.go
S2I incremental builds were failing due to not having the correct authorization
to pull the previously built image.
=> Bug 1704767: S2I incremental build not working

pkg/build/builder/daemonless.go
Log a canonical reference to the image that we push.  The buildah library will stop writing this message directly to stdout on its own starting with https://github.com/containers/buildah/pull/1596.
=> push: log the image's canonical reference

pkg/build/builder/cmd/builder.go, pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_unsupported.go, pkg/build/builder/docker.go
Pass the build's configured `ImageOptimizationPolicy` down to the build logic by keeping track of it in the `DaemonlessClient`.
=> Heed the ImageOptimizationPolicy

pkg/build/builder/cmd/builder.go
Parse $BUILD_STORAGE_OPTIONS, if set, as a JSON string array, so that we can set storage options passed to us by the build controller.
=> Parse $BUILD_STORAGE_OPTIONS to set storage options

pkg/build/builder/dockerutil.go
If the error we get back from attempting to push or pull an image is a multi-error, extend our change from #66 to process each of its component errors as we would have a single error.
=> retryImageAction: strip error wrappings for MultiError members

pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go, pkg/build/builder/source.go
Process $DROP_CAPS (example value: "KILL,MKNOD,SETGID,SETUID,SYS_CHROOT") by splitting it at commas, upper-casing it, prefixing each value with "CAP_" if it doesn't already start with that prefix, and setting it in the `DropCapabilities` list in our `BuildOptions`.
=> Process $DROP_CAPS

CONTRIBUTING.md
The correct file is named Dockerfile-env instead of Dockerfile.env
=> Fixed small typo on documentation.

Dockerfile, Dockerfile-dev, Dockerfile.rhel7, imagecontent/storage.conf, pkg/build/builder/util/consts.go
By turning on fuse-overlayfs, the container can run without the
--privileged flag.
Also setup shared directory to allow images to be shared into
the containers via the volume mounts from the host.
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Change containers to allow building without privilege.

cmd/main.go
@openshift/openshift-team-developer-experience @bparees @nalind  FYI
An initial stab into modfications to openshift/builder in light of the 4.2 global CA injection work, along with reconciling some older TODOs I think are now handled by the build controller
My first openshift/builder PR :-)
=> clean up of some CA mount logic that is now handled by the build controller

Dockerfile, Dockerfile-dev, Dockerfile.rhel7
fuse-overlayfs is not available in RHEL 7.
This is causing ART builds for 4.2 to fail.
=> Remove fuse-overlayfs from Dockerfiles

pkg/build/builder/daemonless.go
Use `util.AddImageNames()` to add the `pushTag` to our just-built image, so that the name we apply will include a "latest" tag if one wasn't directly specified.
The `AddImageNames()` function ultimately expands the name we give it, in the same way that Push() does with the name we give it, so this should resolve cases where we would add a name with `SetNames()` that `Push()` would then be unable to use to find the image.
=> Bug 1746499: Add ":latest" to push tag if none is specified

pkg/build/builder/daemonless.go
When we combine the image name that we pushed to with a digest in order to print the "Successfully pushed..." message, strip out the tag.  Will need to be cherry-picked to fix https://bugzilla.redhat.com/show_bug.cgi?id=1716697.
=> Bug 1716697: Strip the tag from the reference we print after pushing an image

pkg/build/builder/daemonless.go, pkg/build/builder/source.go
This patch sets HTTPProxy option on buildah.CommonBuildOptions to true,
that will cause Buildah to forward HTTPProxy environment variables down
the line.
=> Bug 1747937: Forwarding HTTPProxy environment variables.

cmd/main.go
kubernetes will send a sigterm to signal for a graceful shutdown. builder should listen for the sigterm and exit cleanly without requiring a sigkill.
=> [4.3] Bug 1753247: listen for sigterm and terminate

pkg/build/builder/source.go
@openshift/openshift-team-developer-experience FYI
The registry.conf built by the OCM and passed to openshift/builder should have the correct settings based on what has been supplied to the build config for pulling in source from an image, or from any global image config that has been created.
=> Bug 1755140: do not force skip tls verify to true on image source injection

pkg/build/builder/util/dockerfile/dockerfile.go, pkg/build/builder/util/dockerfile/dockerfile_test.go
When rewriting the Dockerfile with our substitutions, we unconditionally insert `=` characters, even in cases where the original file didn't use them.  They're syntactically important, though, so such changes can cause builds to fail.  For ENV and LABEL instructions, just emit the original text.
Fixes https://github.com/openshift/origin/issues/24151.
=> manage-dockerfile: use the original form of ENV/LABEL

hack/lib/build/version.sh
Avoid:
```
I0207 15:51:43.662541       1 builder.go:425] openshift-builder v4.3.0-202001211731+b93dcc9-dirty
```
in 4.3.0 builder logs, which is from Git looking at the build directory and seeing:
* The commit b93dcc9, which is in the dist-git repository, not in openshift/builder.  The commit hash logged for 4.3.0 should have been:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.3.0-x86_64 | grep builder
docker-builder    https://github.com/openshift/builder    50c6e17276dfc7d0acd9d943dac340fb4fa3ff24
```
* `-dirty` because Doozer is adjusting our `Dockerfile`?
With this commit we pivot to `BUILD_VERSION` and `SOURCE_GIT_COMMIT`, set by Doozer since [here][1] and [here][2] respectively (internal Red Hat links; sorry external folks).  If either is …
=> hack/lib/build/version: Use BUILD_VERSION and SOURCE_GIT_COMMIT if non-empty

pkg/build/builder/util/dockerfile/dockerfile.go, pkg/build/builder/util/dockerfile/dockerfile_test.go
When rewriting the Dockerfile with our substitutions, we unconditionally insert `=` characters, even in cases where the original file didn't use them.  They're syntactically important, though, so such changes can cause builds to fail.  For ENV and LABEL instructions, just emit the original text.
Cherry-picked from #134.
=> [release-4.4] Bug 1821860: manage-dockerfile: use the original form of ENV/LABEL

pkg/build/builder/util/dockerfile/dockerfile.go, pkg/build/builder/util/dockerfile/dockerfile_test.go
When rewriting the Dockerfile with our substitutions, we unconditionally insert `=` characters, even in cases where the original file didn't use them.  They're syntactically important, though, so such changes can cause builds to fail.  For ENV and LABEL instructions, just emit the original text.
Cherry-picked from #134.
=> [release-4.3] Bug 1821861: manage-dockerfile: use the original form of ENV/LABEL

pkg/build/builder/common.go, pkg/build/builder/common_test.go, pkg/build/builder/docker.go
Some of the helper functions that `addBuildParameters()` calls modify the parsed tree, discarding `ARG` instructions that precede the first `FROM` instruction.  The replacement Dockerfile that we generate from that tree would be missing those instructions.
Knowing that this will happen, walk the parsed tree beforehand, recording `ARG` instructions that precede the first `FROM` instruction, and then re-prepend them to the Dockerfile that we generate from our tree after we've finished manipulating it.
If we've got `BuildArgs` in a `DockerStrategy`, populate the `BuildArgs` map that we pass to imagebuilder functions that might have a use for them.
We usually try to pull images that are referenced in the Dockerfile ourselves, so that we can record the time required to pull them.  If we looked …
=> Bug 1842982: preserve ARG values that come before the first FROM

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/imagebuildah/executor.go, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/modules.txt
As the title says, bumping to Buildah v1.14.10.
Addresses this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1844596
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
=> Bug 1844596: Bump buildah to v1.14.10

go.mod, go.sum, vendor/github.com/openshift/imagebuilder/builder.go, vendor/github.com/openshift/imagebuilder/dispatchers.go, vendor/github.com/openshift/imagebuilder/imagebuilder.spec, vendor/github.com/openshift/imagebuilder/internals.go, vendor/modules.txt
Update imagebuilder from v1.1.4 to v1.1.6 to pick up additional fixes for expanding references to ARG values when processing instructions.
=> Bug 1839683: bump github.com/openshift/imagebuilder to v1.1.6

imagecontent/bin/entrypoint.sh
When openshift-builder starts, only run `update-ca-trust extract` if the mounted CA is non-empty.
=> Bug 1826183: Run update-ca-trust if CA is non-empty

Dockerfile.rhel8
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.
=> Add Dockerfile.rhel8

go.mod, go.sum, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/.golangci.yml, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/add.go, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/chroot/run.go, vendor/github.com/containers/buildah/chroot/seccomp.go, vendor/github.com/containers/buildah/copier/copier.go, vendor/modules.txt
Bump github.com/containers/buildah from v1.16.0 to v1.16.4, mainly to pick up https://github.com/containers/buildah/pull/2660 and https://github.com/containers/buildah/pull/2668, but also pulling in https://github.com/containers/buildah/pull/2653 to avoid a potential problem that could occur if/when the seccomp.json in the builder image is updated to start using "errno" actions.
=> Bug 1884610: Upgrade buildah to v1.16.4

pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go, pkg/build/builder/docker.go, pkg/build/builder/sti.go
* Merge node credentials in AuthConfigurations format.
* Ensure node credentials and container pull secrets are always merged.
* Docker strategy: only pull images once.
* Source strategy: merge node credentials when setting up buildah's pull
secrets.
=> Bug 1883803: Fixes to merging node credentials

imagecontent/etc/containers/mounts.conf
`/etc/pki/ca-trust` contains the system trust stores for a wide array of
applications. Making this a mount point in buildah causes the original
data in the base image to overlayed by the contents in the build container.
As a result, `/etc/pki/ca-trust` cannot be altered unless another layer is
added to the image being built via a COPY or ADD instruction.
This will revert the mount of `/etc/pki/ca-trust`, thereby removing the ability
of builds to use the cluster trust bundle. This capability will be restored in
a future OpenShift release as an opt-in enhancement.
=> Bug 1891759: Do not mount /etc/pki/ca-trust in builds

Dockerfile-dev
openshift/builder is now RHEL8 based. Updating Dockerfile-dev to use
Fedora 33 as the base image, as this is publicly accessible and has the
same packages available that CI/OSBS does. Note - ubi8 not used because
tree is not available in the free, public RPM repositories.
=> Move dev Dockerfile to Fedora 33

cmd/builder.go, hack/lib/build/version.sh, pkg/build/builder/cmd/builder.go, pkg/version/version.go
- Determine buildah version vendored in from go modules
- Add buildah version as an ldflag
- Print buildah version as the output to all `version` commands
- Log buildah version with -v=5 or higher
=> Bug 1907407: Print buildah version

hack/lib/build/version.sh
Using -mod=vendor will ensure that libraries are not downloaded from the
internet.
=> Bug 1907407: Use -mod=vendor to determine buildah version

imagecontent/etc/containers/mounts.conf
possible fix for https://bugzilla.redhat.com/show_bug.cgi?id=1916897
history of 4.6.0 bug fix that introduced regression that is being reverted noted in above BZ
=> Bug 1916897: more automount of cluster trust bundle reverts; no longer automount /run/secrets

Dockerfile, Dockerfile-dev, Dockerfile.rhel7, Dockerfile.rhel8, imagecontent/usr/share/containers/seccomp.json, pkg/build/builder/cmd/builder.go, pkg/build/builder/daemonless.go
* Force OCI isolation using runc instead of whatever we're configured for by the build controller (currently, usually chroot) to get control group settings that chroot isolation doesn't implement.
* Replace the default seccomp filter with one based on Fedora 33's, but with mount and umount disabled even for RUN instructions that run as root.
=> Force use of runc, since we know we're privileged, and customize our seccomp filter

pkg/build/builder/cmd/dockercfg/cfg.go, pkg/build/builder/daemonless.go
As part of the triage captured at https://coreos.slack.com/archives/C01JLQ7MB2M for a recent CI incident where a corrupted pull secret caused image pull failures with builds, it became apparent that V(4) trace was minimally needed to more precisely capture the error.
The PR strives to make the error cause more available with default logging.
@stevekuznetsov @alvaroaleman FYI
@openshift/openshift-team-build-api FYI
=> Bug 1918879: better surface dockerconfigjson errors causing image pull errors

cmd/main.go, pkg/build/builder/daemonless.go
/assign @bparees 
@nalind @smarterclayton
=> Bug 1916897: narrow scope of rhsm transient bind mount

pkg/build/builder/docker_test.go, pkg/build/builder/util/dockerfile/instructions.go, pkg/build/builder/util/dockerfile/instructions_test.go
When building from source using docker strategy, keys and values for environment variables from BuildConfig and labels have been marshalled to json strings to put them in quotes and do escaping.
Problem was, this marshalling also escapes HTML symbols `<>&`, which should be allowed for environment variables and labels.
Solution is to process values with `strconv.Quote` function in order to escape only non-printable and control characters.
With the BuildConfig provided in Bugzilla, and my changes I get this result:
```
wyvie@irum-mac ~/go/src/github.com/openshift/builder (fix-build-envars-character-escaping*) $ oc logs -f bc/docker-build
...
STEP 1: FROM quay.io/generic/rhel7:latest
STEP 2: ENV "IncorrectURLFromENV"="http://abc.com/q?key1=value1&key2=value2"
...
STEP 5: ENV …
```
=> Bug 1918153: incorrect escaping of HTML symbols in envars

cmd/main.go, pkg/build/builder/daemonless.go
/assign @bparees ( for bz labels )
needed a manual cherrypick for 4.4 as well to get things to compile
=> Bug 1921965: narrow scope of rhsm transient bind mount; originate it from tmp dir for cases where data can persist

pkg/build/builder/daemonless.go, pkg/build/builder/source.go
Have the builder retry if it fails to pull an image, one which we didn't pre-pull ourselves, during the build.
=> Bug 1937535: retry image pulls during builds

pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go
=> Bug 1940488: add etc-pki-entitlements from pod secrets if available to build container

pkg/build/builder/daemonless.go
Our CI / testplatform team are seeing inexplicably long delays when OpenShift Builds try to pull image content as input prior to building the image.
Some corresponding "end" messages to go with the "start" messages that already exist was deemed helpful in their diagnostic efforts. so they easily demarcate when the openshift/builder image calls out into the vendored buildah/containers code.
/assign @bparees
=> Bug 1943614: add explict exit log after buildah pull image; tweak existing start log priot to buildah pull image call

pkg/build/builder/daemonless.go
```
Pushing image image-registry.openshift-image-registry.svc:5000/foo/busybox:latest ...
Getting image source signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/foo/busybox:latest
Warning: Push failed, retrying in 5s ...
Getting image source signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/foo/busybox:latest
Warning: Push failed, retrying in 5s ...
Getting image source signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/foo/busybox:latest
Warning: Push failed, retrying in 5s ...
error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared]image-registry.openshift-i …
```
=> Bug 1947164: Print "Successfully pushed" only if push succeeded

pkg/build/builder/daemonless.go
manual cherrypick of the 2 4.8 PRs / commits to get consensus on the start/end logging around calls from openshift/builder into the vendored buildah code when builds define `ImageSource` entries and we call buildah to execute the download/copy of those image refs
@stevekuznetsov and the testplatform team is trying to diagnose undo slowness of this function in the CI clusters
they have also already turned on V6 trace for builds in those clusters, but on their next 4.7.x upgrade of the CI clusters, they can get this logging too, as they indicated that would help them.
Ultimately, between build api team and @nalind we can help them pinpoint where the delays are occurring.
/assign @bparees 
i.e. this is the redo of the 4.7 PR I assigned to you, but then we agreed to close, yesterday
=> Bug 1943726: add bracket logging on openshift/builder calls into buildah to assist test-platform team triage

go.sum, imagecontent/etc/containers/mounts.conf, pkg/build/builder/daemonless.go
manual pick of https://github.com/openshift/builder/pull/240 required
among other things, I got this error running `make test`, `go mod tidy`, `go mod vendor` 
```
verifying github.com/openshift/source-to-image@v1.3.0: checksum mismatch
downloaded: h1:YDEH0PY0sMaUNbpJAGnDZA94tkAD6qi1Rou8ycWRPRc=
go.sum:     h1:ZktIgJ85Vn0HOyHdS6uQOMXhmYwc5h76w/6LpnJ60L8=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
```
so there is a separate commit to fix `go.sum` and make the noted commands happy
=> Bug 1946363: move entitlement related secrets back to mounts.conf

pkg/build/builder/dockerutil.go, pkg/build/builder/dockerutil_test.go, pkg/build/builder/util_linux.go
/assign @nalind 
there was no existing unit testing around `GetCGroupLimits()` or `readIn64` that I saw
the simplicity of the fix did not motivate me to take that on, but of course am curious on your respective takes
=> BUILD-278: Check cgroup v1 and cgroup v2 Files for Quota

Dockerfile, Dockerfile-dev, Dockerfile.rhel7, Dockerfile.rhel8, cmd/builder.go, cmd/defaults.go, cmd/main.go, cmd/userns.go, go.mod, go.sum, pkg/build/builder/cmd/builder.go, pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_unsupported.go, pkg/build/builder/dockerutil.go, pkg/build/builder/dockerutil_test.go
Add CLI flags for controlling the type of process isolation we use for `RUN` instructions, and for controlling the storage driver and options that we pass to it, along with logic for guessing the right defaults.  Drop environment variables that controlled these settings.  This renders the static `storage.conf` file in the builder image largely irrelevant.
~~Add `/etc/subuid` and `/etc/subgid` files to the builder image that allow root to map the entire ID namespace.~~
Have the docker and sti builders re-exec themselves in user namespaces when they're run as non-UID=0 or without the `CAP_SYS_ADMIN` capabiity, so that they will be able to create new namespaces when processing RUN instructions.
With no CLI flags supplied and in a privileged pod, the builder should continue using the overlay …
=> unprivileged: add CLI options for isolation and storage

cmd/main.go, pkg/build/builder/transient_mounts.go
Walk back a bit of #220: don't assume that we can set up a user namespace when we're invoked as openshift-manage-dockerfile or openshift-git-clone, even when not explicitly given mappings to use, since those containers haven't traditionally been run with privileged=true.
=> unprivileged: don't try to set up user namespaces for manage-dockerfile/git-clone

pkg/build/builder/cmd/builder.go
Let the serviceability package decide how to map klog logging levels to logrus levels.  Per [InitLogrusFromKlog](https://github.com/openshift/library-go/blob/9396bd4bf9966d7c7827d8eeb38d80b6bb311cb6/pkg/serviceability/logrus.go#L13), this has the effect of changing the logging level assumed for debug-level messages from 6 to 4.
=> Let the serviceability package determine how to tie logrus to klog

Dockerfile, Dockerfile-dev, Dockerfile.rhel7, Dockerfile.rhel8
Our base images don't preserve file capabilities on `/usr/bin/newuidmap` and `/usr/bin/newgidmap`, but they do preserve setuid/setgid bits, which grant more privileges to callers, so go ahead and restore file capabilities during the build.
=> Dockerfiles: run `rpm --setcaps shadow-utils` during build

pkg/build/builder/sti.go, pkg/build/builder/sti_test.go
If the s2i assemble image's configured user includes a group (i.e., the user spec is in the form "user:group"), strip the group part before checking if the UID is in the range of allowed users.  Borrow `extractUsers()` from `github.com/openshift/source-to-image/pkg/docker` to handle it.
=> Bug 2021551: getAssembleUser(): strip the group part out before checking the UID

cmd/userns.go
When complaining about not being able to find any ID mapping ranges for the current user, include the user's name in the error message.
=> Report User/Group ID when they cannot be parsed

cmd/defaults.go, cmd/userns.go, cmd/userns_test.go
When we create a new user namespace so that we can get CAP_SYS_ADMIN over a mount namespace, if we're already UID 0, map the current set of ID mappings over themselves instead of trying to repeat the mapping that's been applied to the container we're in.
If we know we've been started in a namespace that doesn't have node-default mappings, log that we know.
Don't default to trying "metacopy=on" with "mount_program=fuse-overlayfs", since it knows nothing about the option and all we do is trigger a repeated warning about it not being recognized.
=> BUILD-433: use the right mappings when we don't need to set any

pkg/build/builder/daemonless.go
Add --quiet option to buildah if log level is less than 2
=> Bug 1996883: Add --quiet option to buildah if log level is less than 2

pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go
Checks for empty BUILD_LOGLEVEL environment variable before attempting
to convert it's content to an integer
=> Bug 2071364: invalid syntax when parsing empty BUILD_LOGLEVEL

cmd/main.go
Bring back `--loglevel` as a recognized CLI option, to make it easier to test using older versions of the controller manager (i.e., older clusters).
=> main(): accept --loglevel as an alias for -v

cmd/userns.go
Set _CONTAINERS_USERNS_CONFIGURED instead of BUILDER_USERNS_CONFIGURED in the environment if we create our own user namespace, so that various bits of logic that depend on detecting that we're in a rootless mode will do what we need them to do.
In this instance, that's setting extended attributes with names starting with "user.\*" instead of "trusted.\*" when applying layers to disk while pulling images.
=> Set _CONTAINERS_USERNS_CONFIGURED if we create a user namespace

pkg/build/builder/daemonless.go
Adds the option to set the environment variable BUILDAH_QUIET
on the build config which will enable Buildah's --quiet option
on the build.
=> Bug 2099991: Add support for BUILDAH_QUIET environment variable

pkg/build/builder/util/dockerfile/dockerfile.go, pkg/build/builder/util/dockerfile/dockerfile_test.go
When reconstructing the Dockerfile, use the original version of a HEALTHCHECK instruction, rather than incorrectly reassembling all of the arguments into a single JSON array.
=> OCPBUGS-6014: manage-dockerfile: use the original form of HEALTHCHECK

CONTRIBUTING.md
While following the steps of [Testing on OpenShift](https://github.com/openshift/builder/blob/master/CONTRIBUTING.md#testing-on-an-openshift-cluster), the patch command failed with the following error:
~~~
$ oc patch clusterversion/version --patch '{"spec":{"overrides":[{"kind":"ConfigMap", "namespace":"openshift-controller-manager-operator","name":"openshift-controller-manager-images","unmanaged":true}]}}' --type=merge
The ClusterVersion "version" is invalid: spec.overrides.group: Required value
~~~
This was tested with `oc` client version v4.10.45 as well as v4.12.0.
Added the `group: v1` to meet the patch required syntax, and the patch was successful.
=> Modified clusterversion patch command

go.mod, vendor/modules.txt
Fixes [2023-02-13 16:08:21,502 cachito.workers ERROR __init__.run_cmd] The command "go list -mod readonly -m -f {{ if not .Main }}{{ .String }}{{ end }} all" failed with: go: k8s.io/dynamic-resource-allocation@v0.0.0: reading https://cachito-athens.cachito-prod.svc/k8s.io/dynamic-resource-allocation/@v/v0.0.0.info: 404 Not Found
=> OCPBUGS-7412: Fix k8s.io/dynamic-resource-allocation error

go.mod, go.sum, vendor/github.com/containers/common/libnetwork/netavark/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Bump github.com/containers/common from v0.51.0 to v0.51.2, which puts CAP_SYS_CHROOT back into the default list of capabilities that we grant when handling RUN instructions.
=> OCPBUGS-7782: bump(github.com/containers/common) to v0.51.2

pkg/build/builder/common.go, pkg/build/builder/common_test.go, pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go, pkg/build/builder/source.go, pkg/build/builder/sti.go, pkg/build/builder/testdata/credentials-http-redhatio-nodeuser.json, pkg/build/builder/testdata/credentials-https-quayio-user0.json, pkg/build/builder/testdata/credentials-https-redhatio-nsuser.json, pkg/build/builder/util.go, pkg/build/builder/util/dockerfile/dockerfile.go, pkg/build/builder/util/dockerfile/dockerfile_test.go, pkg/build/builder/util_test.go
Normalize locations in secrets that look like URLs, since we used to accept (or "accept") those.
Updates mergeNodeCredentials(), used by the image pulling logic. Updates mergeNodeCredentialsDockerAuth(), used by the docker and sti strategies. Updates extractSourceFromImage() directly, since it doesn't use either of the other functions.
=> OCPBUGS-3064: normalize locations in pull/push secrets which might look like URLs

pkg/build/builder/daemonless.go, pkg/build/builder/docker.go, pkg/build/builder/dockerutil.go, pkg/build/builder/dockerutil_test.go, pkg/build/builder/util_linux.go
Teach `pkg/build/builder.GetCGroupLimits()` to read cgroups v1 "cpu.shares", "cpu.cfs_quota_us", and "cpu.cfs_period_us" files, and to read more or less equivalent values from v2 "cpu.max" and "cpu.weight" files.
When reading v2 values, scale the "cpu.weight" from the v2 [1..10000] weight range to the v1 [2..0x40000] share range, and scale the "cpu.max" values from the v2 [0..100000] range to the v1 [0..1000000] ranges.
Pick up @coreydaley's changes from #340 to set CPU limits when using the Docker strategy.
=> OCPBUGS-1973: pass CPU limits for Docker strategy builds

README.md
Adding reference to Contributing.md for someone looking for "how to contribute/where to start".
I've tried to keep it short. Open to suggestions to make it more relatable to the community/end-users :).
=> OCPBUGS-14798: Adds reference to contributing.md

cmd/userns.go, pkg/build/builder/cmd/builder.go, pkg/build/builder/daemonless.go, pkg/build/builder/daemonless_test.go, pkg/build/builder/transient_mounts.go, pkg/build/builder/transient_mounts_test.go
Mount secrets as "overlay" mounts, so that we can more easily mark them as noexec/nosuid/nodev in unprivileged builds, where attempting to change the mount flags on a bind mount in an unprivileged namespace would trigger errors.
Log which capabilities we have at startup at level 2 or higher, and use the newer API to check if we have CAP_SYS_ADMIN.
=> BUILD-432: mount secrets as "overlay" mounts

cmd/main.go, cmd/userns.go, go.mod, go.sum, pkg/build/builder/cmd/builder.go, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/chroot/run_linux.go, vendor/github.com/containers/buildah/chroot/seccomp.go, vendor/github.com/containers/buildah/chroot/seccomp_freebsd.go, vendor/github.com/containers/buildah/chroot/seccomp_unsupported.go, vendor/github.com/containers/buildah/define/types.go, vendor/github.com/containers/buildah/run_linux.go, vendor/modules.txt
* bump github.com/containers/buildah from v1.32.0 to v1.32.1 to get improvements in how its chroot logic handles bind mounts when the read-only mount option is combined with nodev/noexec/nosuid being used at the source of the bind mount
* wire up klog's CLI flag parsing to main, making the old `--loglevel` option a proper alias for its `--v` option, and exposing klog's other flags
* also log when we're started with node-default user namespace mappings, so that tests of unprivileged builds will be able to tell the difference between running in a user namespace (the log message we already emitted at level 2), not running in a user namespace (a new log message at level 2), or a problem turning up the logging level (which was previously indistinguishable from the …
=> OCPBUGS-23128: bump github.com/containers/buildah to fix transient mounting in chroot isolation

go.mod, go.sum, vendor/github.com/openshift/api/build/v1/consts.go, vendor/modules.txt
The current vendored version of openshift/api doesn't include the changes merged with https://github.com/openshift/api/pull/1674. This commit bumps the openshift/api to the latest release-4.15 branch.
=> OCPBUGS-35283: Bumps openshift/api & related dependencies

pkg/build/builder/source_test.go
Recent git upgrade to fix a CVE is causing some issues lately for the unit tests. The git upgrade disabled file protocol by default which is causing the problem.Those tests are skipped as they are duplicate.
=> OCPBUGS-45321: skipping some unit tests to avoid failures as they are duplicate

CONTRIBUTING.md, README.md
Clean up the README and contributing guide so it is easier to comprehend and provide fuller context to contributors.
The original README was a bare document that was mostly untouched after OpenShift 4.0 was released. Most of the contributors at the time were OpenShift veterans and had deep "head knowledge" of how OpenShift worked; a fully detailed README or contributor guide was not a top priority. This update provides fuller context to contributors, linking out to the openshift-controller-manager repository and Red Hat's official docs for Builds with BuildConfig.
The contributor guide is restructured with a more natural developer progression (set up, clone, compile, test, deploy). Deploy instructions are updated to reference cluster-bot for Red Hat employees, and self- managed install …
=> OCPBUILD-174: Refresh CONTRIBUTING Guide

hack/lib/build/binaries.sh
We no longer need to test if we are building with go modules and the `-mod vendor` mode; always build with `-mod vendor` because vendoring dependencies is an OpenShift standard practice.
=> OCPBUILD-174: Always Build with `-mod vendor`

go.mod, go.sum, vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go, vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c, vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go, vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go, vendor/modules.txt
runc golang package is bumped from 1.1.9 to 1.1.12 to fix the CVE-2024-21626
=> OCPBUGS-43186: runc library bump to 1.1.12

go.mod, go.sum, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/Makefile, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/define/types.go, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/github.com/containers/buildah/install.md, vendor/github.com/containers/buildah/internal/open/open.go, vendor/github.com/containers/buildah/internal/open/open_linux.go, vendor/github.com/containers/buildah/internal/open/open_types.go, vendor/github.com/containers/buildah/internal/open/open_unix.go, vendor/github.com/containers/buildah/internal/open/open_unsupported.go, vendor/github.com/containers/buildah/internal/parse/parse.go, vendor/github.com/containers/buildah/internal/types.go, vendor/github.com/containers/buildah/internal/volumes/bind_linux.go, vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go, vendor/github.com/containers/buildah/pkg/overlay/overlay.go, vendor/github.com/containers/buildah/run.go, vendor/github.com/containers/buildah/run_linux.go, vendor/modules.txt
Bumping `buildah` from 1.26.6 to 1.26.9 to fix [CVE-2024-9675](https://github.com/advisories/GHSA-586p-749j-fhwp)
=> OCPBUGS-43296: Bump buildah to 1.26.9

pkg/build/builder/util_linux.go
Problem:
When CPU limits are configured in the BuildConfig, applications running in the assemble script do not observe CPU values higher than 1 core. Any CPU limits set above 1 are rounded down to 1, causing builds to take longer and significantly reducing performance.
Solution:
Removing the condition that caps the cpuQuota at 1,000,000 (i.e. 1 cpu limit). This hard limit was causing CPU limit configured in the BuildConfig to be rounded down to 1 core if they exceeded that threshold of 1,000,000.
=> OCPBUGS-56106: S2I build cpu limits observed by assemble are limited to 1 cpu
