cmd/main.go, pkg/build/builder/util.go
JIRA IDs: DEVEXP-181, DEVEXP-182
=> Copy CAs mounted via ConfigMap

Dockerfile.rhel7
Testing a PR job for building RHEL images
=> WIP: image: Add a test dockerfile for rhel7

cmd/main.go
Additional trusted CA certs and the registry's CA cert will be mounted into `/var/run/openshift.io/certs/certs.d`, which is then copied into `/etc/docker/certs.d`.
See https://github.com/openshift/origin/pull/21614
=> copy build certificates to /etc/docker/certs.d

imagecontent/registries.conf
Additional doc comments added from containers/image
=> Limit Default Search to docker.io

pkg/build/builder/common.go
/assign @gabemontero 
fyi @smarterclayton
=> Fix empty name in status update

pkg/build/builder/source.go
https://bugzilla.redhat.com/show_bug.cgi?id=1694864
=> bug: 1694864 - only log error if there is one

pkg/build/builder/daemonless.go, pkg/build/builder/source.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1694861
Tests will be in a follow up PR for the origin repo,
=> Do not print credentials into build log

pkg/build/builder/sti.go, pkg/build/builder/sti_test.go
S2I needs to know the AssembleUser before it generates
the Dockerfile, otherwise a hard-coded default is used.
Replicate the logic in source-to-image:
1. Default to the most recent USER in the image
2. Override if the io.openshift.s2i.assemble-user label exists
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1696756
=> Bug 1696756: Fix Assemble User in S2I builds

pkg/build/builder/dockerutil.go
If the error we're reporting for a push or pull is an `ErrUnauthorizedForCredentials` error, strip out the context that other API layers have added, which tends to be a few copies of the image name, which we've previously logged, so that our error message looks like `After retrying %d times, pulling/pushing image still failed due to error: unable to retrieve auth token: invalid username/password`, per https://bugzilla.redhat.com/show_bug.cgi?id=1703262
=> retryImageAction: strip error wrappings for ErrUnauthorizedForCredentials

pkg/build/builder/daemonless.go
Attempt to set the limit on open files and processes while we're building an image to 0x100000 (1048576), overriding the default open files limit that we get when generating a runtime configuration.
=> Raise file and process limits before building an image

Makefile
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Start using Buildah versus Docker for building container images

LICENSE
=> Adding LICENSE file to project

Dockerfile, Dockerfile.rhel7
Follow up to https://github.com/openshift/release/pull/5552
/assign @gabemontero
=> Bump golang version to 1.12

go.mod, go.sum, vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go, vendor/github.com/openshift/source-to-image/pkg/util/labels.go, vendor/modules.txt
=> bug 1781793: bump revert s2i bump for 1758305

go.mod, go.sum, vendor/github.com/openshift/source-to-image/pkg/api/constants/scripts.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go, vendor/github.com/openshift/source-to-image/pkg/util/labels.go, vendor/modules.txt
=> Bug 1781795: bump revert s2i bump for 1758305

go.mod, go.sum, vendor/github.com/mtrmac/gpgme/.appveyor.yml, vendor/github.com/mtrmac/gpgme/.travis.yml, vendor/github.com/mtrmac/gpgme/data.go, vendor/github.com/mtrmac/gpgme/go.mod, vendor/github.com/mtrmac/gpgme/go_gpgme.c, vendor/github.com/mtrmac/gpgme/go_gpgme.h, vendor/github.com/mtrmac/gpgme/gpgme.go, vendor/github.com/mtrmac/gpgme/unset_agent_info.go, vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go, vendor/modules.txt
Fixes [CVE-2020-8945](https://access.redhat.com/security/cve/CVE-2020-8945)
=> [release-4.3] Bug 1802894: bump(github.com/mtrmac/gpgme): v0.1.2

cmd/glogflags.go, cmd/main.go, pkg/build/builder/cmd/builder.go, pkg/build/builder/common.go, pkg/build/builder/common_test.go, pkg/build/builder/daemonless_unsupported.go, pkg/build/builder/docker.go, pkg/build/builder/docker_test.go, pkg/build/builder/source.go, pkg/build/builder/source_test.go, pkg/build/builder/sti.go, pkg/build/builder/sti_test.go, pkg/build/builder/timing/context.go, pkg/build/builder/util.go, pkg/build/builder/util/logging.go, pkg/build/builder/util/logging_test.go, pkg/build/builder/util_linux.go
=> Clean up imports

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/github.com/containers/buildah/pkg/blobcache/blobcache.go, vendor/modules.txt
=> [release-4.5] Bug 1868401: bump(containers/buildah):

go.mod, go.sum, vendor/github.com/openshift/imagebuilder/README.md, vendor/github.com/openshift/imagebuilder/builder.go, vendor/github.com/openshift/imagebuilder/dispatchers.go, vendor/github.com/openshift/imagebuilder/dockerfile/parser/parser.go, vendor/github.com/openshift/imagebuilder/imagebuilder.spec, vendor/github.com/openshift/imagebuilder/internals.go, vendor/modules.txt
Update imagebuilder to v1.1.7, which should fix https://bugzilla.redhat.com/show_bug.cgi?id=1843727.
=> Bug 1843727: bump github.com/openshift/imagebuilder to v1.1.7

Dockerfile, Dockerfile-dev, Dockerfile.rhel7, go.sum, imagecontent/usr/share/containers/seccomp.json, pkg/build/builder/cmd/builder.go, pkg/build/builder/daemonless.go
manual pick of @nalind 's https://github.com/openshift/builder/pull/207 required
/assign @nalind 
/assign @crawford 
/assign @jupierce 
@bparees FYI
=> Force use of runc, since we know we're privileged, and customize our seccomp filter

cmd/main.go, pkg/build/builder/daemonless.go
/assign @bparees (perhaps for valid bz label)
manual pick since bot got merge conflict with 4.6 PR
Or should we reference one of the BZs Sam opened?
=> Bug 1921966: narrow scope of rhsm transient bind mount

pkg/build/builder/cmd/dockercfg/cfg.go, pkg/build/builder/daemonless.go
manual pick cause bot failed for https://github.com/openshift/builder/pull/200#issuecomment-765507917
=> [release-4.6] Bug 1919359: better surface dockerconfigjson errors causing image pull errors

go.mod, go.sum, vendor/github.com/containernetworking/cni/pkg/invoke/find.go, vendor/modules.txt
=> Bug 1924554: bump(cni) 0.8.1

pkg/build/builder/daemonless.go
see https://coreos.slack.com/archives/C014MHHKUSF/p1616690484100700
@stevekuznetsov
=> Bug 1943614: add enter/exit logging around buildah pull image

imagecontent/etc/containers/mounts.conf, pkg/build/builder/daemonless.go
manual pick of https://github.com/openshift/builder/pull/238 needed
/assign @bparees
=> Bug 1945692: move entitlement related secrets back to mounts.conf

go.mod, go.sum, vendor/github.com/openshift/source-to-image/pkg/api/types.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/dockerfile/dockerfile.go, vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go, vendor/github.com/openshift/source-to-image/pkg/scm/git/url.go, vendor/github.com/openshift/source-to-image/pkg/scripts/install.go, vendor/github.com/openshift/source-to-image/pkg/util/labels.go, vendor/modules.txt
we were wrong with https://github.com/openshift/builder/pull/179
=> Bug 1971332: bump(s2i): revert incorrect ssh scp fix

go.mod, go.sum, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/copier/copier.go, vendor/github.com/containers/buildah/define/types.go, vendor/modules.txt
Bump buildah from v1.22.3 to v1.22.4, incorporating https://github.com/containers/buildah/pull/3739.
=> Bug 2044244: bump(github.com/containers/buildah) to v1.22.4

Dockerfile.rhel8
=> OCPBUGS-15497: Add the git-lfs package

OWNERS
This is a manual cherry-pick of #379
=> [release-4.13] Replace 'coreydaley' with 'sayan-biswas'

OWNERS
Add team members to the OWNERS file for PR reviews and approvals
=> OCPBUGS-47526: Add team members to the OWNERS file

OWNERS
Added new team members to the OWNERS file
=> OCPBUGS-48655: Add new team members to the OWNERS file
